trigger: 
 - main

pool:
  name: Test

variables:
  artifactName: 'microservices'

steps: 
- task: GoTool@0
  inputs:
    version: '1.17.7'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
- task: Go@0
  inputs:
    command: 'build'
- task: CopyFiles@2
  inputs:
    Contents: '$(artifactName).exe'
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'